apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-denjihost
spec:
  selector:
    matchLabels:
      app: api-denjihost
  template:
    metadata:
      labels:
        app: api-denjihost
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080" 
        prometheus.io/path: "/swagger-stats/metrics"
    spec:
      containers:
        - name: api-denjihost
          image: api-denjihost
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - name: api-port
              containerPort: 8080
          env:
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-denjihost-secret-dev
                  key: jwt-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-denjihost-secret-dev
                  key: db-url
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-denjihost-config-dev
                  key: API_PORT

