apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-denjihost
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-denjihost
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
