apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- secret.yaml
- hpa.yaml
- service-monitor.yaml


images:
- name: api-denjihost
  newName: qzzdocker24/api-denjihost
  newTag: 849b01a6c811e7740b8b8548ec40f2172b21ce9d
