apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-denjihost-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GabSnow24/k8s-denjihost.git
    targetRevision: HEAD
    path: kube/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: api-denjihost
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
