# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ms-wpp
# spec:
#   selector:
#     matchLabels:
#       app: ms-wpp
#   template:
#     metadata:
#       labels:
#         app: ms-wpp
#       annotations:
#         prometheus.io/scrape: "true"
#         prometheus.io/port: "8080" 
#         prometheus.io/path: "/metrics"
#     spec:
#       containers:
#         - name: ms-wpp
#           image: ms-wpp
#           resources:
#             limits:
#               memory: '128Mi'
#               cpu: '500m'
#           ports:
#             - name: ms-port
#               containerPort: 8080
#           env:
#             - name: RABBIT_URL
#               valueFrom:
#                 configMapKeyRef:
#                   name: ms-wpp-config-dev
#                   key: RABBIT_URL
          
