# apiVersion: v1
# kind: Service
# metadata:
#   name: ms-wpp
# spec:
#   selector:
#     app: ms-wpp
#   ports:
#     - name: ms-service-port
#       port: 80
#       targetPort: ms-port
#   type: LoadBalancer
